### ISSUE TITLE
Why Trainer Level is fixed to 26 

### ISSUE THREAD

**Issue by NasirSabasoft** [goatslacker/pokemon-go-iv-calculator#3]
I cannot understand trainer level is being fixed to 26 during calculations.
Can you explain it plz

**Comment by goatslacker** [comment]
Because my trainer level is 26. Actually it's 27, I just leveled up yesterday.

I made it configurable through the web interface though.

**Comment by NasirSabasoft** [comment]
Thanks bro its really great helpful 👍
