### ISSUE TITLE
What is the pokemon level

### ISSUE THREAD

**Issue by tolbard** [goatslacker/pokemon-go-iv-calculator#4]
Hi it's look great

But I have 2 small questions. What do you enter in the pokemon Level? 
is it the number of power-up for this pokemon or something else?

Also when do you use this ivcalculator ? 
- Just when you catch a new Pokemon
- Any time even with old Pokemon
- just when you hatch an egg
- after the first or second powerup

**Comment by goatslacker** [comment]
**What is Pokemon Level?**

If you know your Pokemon's level you enter it in there. The Pokemon's level is the position of the dot in the white arc that sits above your Pokemon's picture, where the CP is at. It's relative to your label so it's a bit difficult to determine. If you're aware of how these work you can figure out the level and enter it in for better accuracy.

**When do you use this?**

I use it every time I catch a new Pokemon. I need a question answered, should I transfer this Pokemon or should I keep it? This gives me a good indication whether a Pokemon is worth keeping around for later evolving into taking gyms or if I transfer it for candy.

I never check after that. If it's in my inventory I assume it's good and evolve it when I get the chance starting with the highest CP'd Pokemon. In the off chance that I keep a crappy Pokemon then I'll nickname it something.

If you want to find it's exact IVs then you can power up your Pokemon a few times and each time check its IVs. The exact value will be the one that intersects between all results. I usually never care for exact values as they're sort of meaningless...a Pokemon is either good enough, perfect, or candy fodder.

**Comment by tolbard** [comment]
@goatslacker 
Sorry to disturb you again . Note before when you say "relative to your label" is this level?

If I understand well you  give a level from 0 to 4  and it base on the position of the white dot in the white arc. This gone be use to get the a value from the dust-to-level.json.  Can you just confirm if I am right?

![image](https://cloud.githubusercontent.com/assets/1523058/17834646/f8e21406-678d-11e6-82fb-141a0bc31511.png)

![image](https://cloud.githubusercontent.com/assets/1523058/17834683/c4db8dd0-678e-11e6-83d7-0dc36fc93c15.png)

**Comment by goatslacker** [comment]
No that's wrong. There are 40 pokemon levels with half levels in between so a grand total of 80 unique "points".

If you're trainer level 27 then the maximum level a pokemon could be "maxed out" would be 28.5. It's always trainer level + 1.5

Also, eggs always hatch at level 20.
