### ISSUE TITLE
`Not found` for some pokemons.

### ISSUE THREAD

**Issue by ozbillwang** [goatslacker/pokemon-go-iv-calculator#6]
Got most result, but not below:

```
name,cp,hp,stardust,leveled,minIV,maxIV
nidoran,443,72,2500,false,Not found,Not found
nidoran,437,67,3000,false,Not found,Not found
nidoran,482,62,3000,false,Not found,Not found
sparky,1171,86,3000,false,Not found,Not found
```

And powerup a `36~87` vaporeon, and get `22~47` IV. Will this be right?

```
# Before power up: 
vaporeon,1663,167,3000,false,36,87

# After power up:
vaporeon,1700,169,3500,false,22,47
```

**Comment by goatslacker** [comment]
Sparky is not a valid Pokemon name. Neither is "nidoran" there is "nidoran_female" and "nidoran_male"

Those values do work however:

http://pocketmaster.surge.sh/#/iv/nidoran_female/443/72/2500

and yes that Vaporeon is correct. Before power up it was between 36-87% now it's between 22-47% I recommend you appraise and figure out where in the bracket you're at.
