### ISSUE TITLE
Pokemon.json out of date

### ISSUE THREAD

**Issue by bflora** [goatslacker/pokemon-go-iv-calculator#7]
I noticed Muk's moves are incorrect.  I've not found a full parse-able list of the current moves anywhere.  Thanks for your work on this!

**Comment by goatslacker** [comment]
I'll check it out. Which moves are incorrect?

**Comment by bflora** [comment]
I just did a line by line comparison with pokemongodb's data to update my file by hand.  I only found 3 discrepancies:

Muk should have Gunk Shot
Staryu should have Tackle
polygon should have Zen Headbutt

**Comment by goatslacker** [comment]
Ah from last update. Staryu's Quick Attack was retired in favor of Tackle. I'll make the updates.

**Comment by bflora** [comment]
Awesome.

**Comment by goatslacker** [comment]
It's super up to date now.
