### ISSUE TITLE
Pokemon max CP buff?

### ISSUE THREAD

**Issue by bflora** [goatslacker/pokemon-go-iv-calculator#8]
How does this project need to be updated to accomodate the recent CP buffs?

New values are here: https://docs.google.com/spreadsheets/d/18nPeu4lrYmF4r_kx_JMB9KL968Dqb_V5O16V6uuTk5s/htmlview?usp=sharing&sle=true

**Comment by goatslacker** [comment]
Oh yeah sorry I updated this on the website long ago. Let me merge the new changes in.

**Comment by goatslacker** [comment]
Closing this because it's been updated.
