### ISSUE TITLE
Missing gen 2 pokemons

### ISSUE THREAD

**Issue by vibou** [goatslacker/pokemon-go-iv-calculator#9]
Pokemons and moves from gen2 pokemons is not in the list. Please add them :)

**Comment by goatslacker** [comment]
I haven't added them because just the babies have been released + togetic, they're all awful for gyms.

Once we get a wider release I'll add in all of gen2.

**Comment by goatslacker** [comment]
I'm not opposed to having them added though, if you're feeling it then send a PR and I'll def merge it in!
